### ISSUE TITLE
关于这个仓库日益爆炸的思考

### ISSUE THREAD

**Issue by wdpm** [dd-center/bilibili-vtuber-danmaku#10]
该仓库记录了bilibili vtuber直播间的弹幕，2000+量级的vtuber数量，加上近两年（2019-2020）的时间跨度。
事实上，已经数据量已经很大了，有点滥用github当网盘的感觉。

### 数据削减建议
- **时间跨度的保留范围缩窄**。将时间设定为只保留近三个月左右。（这个时间跨度长度只是举例）。就能极大程度削减数据量，除非真的有一些需要保留近2年的弹幕的功能要求？
- **启用文本数据压缩**。类似于代码的uglify，清除一切空格。第一，决定文本格式。是JSON，txt，还是自定义分隔格式？
例如JSON minify。这个方法也能在一定程度上削减数据量。

@simon300000

**Comment by wdpm** [comment]
定期清理功能可以借助github actions，写一个cron job。每晚走一次，执行清理。

**Comment by simon300000** [comment]
这种纯文本啦，还是gzip好用吧哈哈

**Comment by wdpm** [comment]
gzip的话。每次处理就要又解压一遍，处理完后又gzip一遍.......。弹幕archive这种情况应该属于文件数量很多，但是每个文件的平均的大小不大的情况。个人认为无脑gzip不是一种好办法。还是minify比较好。

此外，时间跨度问题呢，真的有保存2年那么长的必要吗？
@simon300000

**Comment by wdpm** [comment]
把它看做定期清log就好了，别想这么复杂。

**Comment by simon300000** [comment]
这里面好像没什么空格呀，minify有效吗

**Comment by wdpm** [comment]
我意思是minify成一行，很长的那种。你找个压缩后的js文件看下就明白了。空格和换行都不要，榨干任何能榨的性能。
其次，文本压缩不是主要矛盾。
主要问题是之前你可能欠考虑，没有建立上述那种短期清理的机制，导致数据量无限膨胀。这点，如果还不采取行动的话，估计clone这关就直接劝退我了。

**Comment by simon300000** [comment]
哈哈 要解决这个问题还不如按时间打包zip

**Comment by simon300000** [comment]
按时间打包压缩挺好的，改成别的格式似乎也少不了多少空间

**Comment by wdpm** [comment]
打包依然没有解决问题关键吧。主要还是要清掉那些年代久远的弹幕，个人真的觉得不需要再保留。例如2019年的，丢了吧

**Comment by pren1** [comment]
你好，有保留两年弹幕的需求的。你不用不代表别人不用

**Comment by pren1** [comment]
实际clone下来，其实也就五个G左右（？）在现在这个时间，实在算不上大

**Comment by wdpm** [comment]
举个例子。假设现在20G，清理年代久远的，例如只保留近6个月这样。变成4G。这样就能建立起一种遏制数据爆炸的机制。文本继续采用压缩，只不过是锦上添花，变成3G这样。

**Comment by wdpm** [comment]
既然有无限年代弹幕的需求，就当我没说过，我的错。这个问题我不参与了。

**Comment by simon300000** [comment]
折中一下，也可以把每年的zip打包传到release上

**Comment by pren1** [comment]
我们要用弹幕来分析，训练神经网络。这个还是某个同传网站数据的最后备份。而且再过一年，数据也不会太大（那时候没准V圈都不一定在了）祝好。
