### ISSUE TITLE
这边记录的数据缺失很多人，可否让ddathome帮助记录vdb内容同步

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/bilibili-vtuber-danmaku#25]
就，查了些数据，都好老了，能让大家选择监听直播间的一起贡献这些感觉会好很多？

**Comment by simon300000** [comment]
…老吗？

**Comment by wudifeixue** [comment]
噢，我的意思是，以前加的v都在，但是稍微新的一些人，例如小N就查不到了

**Comment by simon300000** [comment]
😨怎么会这样

**Comment by simon300000** [comment]
😡
https://github.com/dd-center/bilibili-vtuber-danmaku/tree/master/danmaku/363889

**Comment by wudifeixue** [comment]
草，原来是按照直播间id的吗？我晕了

**Comment by simon300000** [comment]
哈哈哈哈哈哈哈
