### ISSUE TITLE
压缩一下再上传？

### ISSUE THREAD

**Issue by taseikyo** [dd-center/bilibili-vtuber-danmaku#8]
实在是太大了🤦‍，克隆要半天
目前加上 `.git` 文件夹一共 20G 左右（纯弹幕 15G），再往后估计要爆炸了
每个 txt 弹幕文件压缩之后再传应该能省不少
我试了一个 v 的弹幕，压缩前是 90+M，压缩后是 30+M
减少的空间还蛮多的，按这么算 15G->5G 能节省不少下载时间😂

**Comment by simon300000** [comment]
的确 这个repo现在越变越大了
压缩可能会上传到一个新的repo，每次都force的方式保持没有git commit
我能问问是怎么用的吗？我觉得提供github pages的形式应该也有可能→_→

**Comment by taseikyo** [comment]
> 的确 这个repo现在越变越大了
> 压缩可能会上传到一个新的repo，每次都force的方式保持没有历史
> 我能问问是怎么用的吗？我觉得提供github pages的形式应该也有可能→_→

支持压缩+force 上传方式，反正要的是弹幕，也没人关心历史记录（
至于怎么用的，昨天看到这个r于是建个了 repo：https://github.com/taseikyo/gachi ，开开脑洞自娱自乐，后续或许可能水水视频啥的😂
